// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyytukclptderwcmuhkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5eXR1a2NscHRkZXJ3Y211aGtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjIwNzQsImV4cCI6MjA2NTQ5ODA3NH0.z_TBwlgEg73sGOO2ko0l3FJz10oKfWn_DBVEe5jSfOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);